name: Test Hello World Docker Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Pull Hello World Docker Image
        run: |
          docker pull hello-world

      - name: Run Hello World Docker Container
        run: |
          docker run -d --name hello-world-container hello-world
        
      - name: Test Hello World Container
        run: |
          sleep 5
          docker logs hello-world-container

