name: Test Hello World Docker Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-container:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Compose
      - name: Run Docker Compose
        run: |
          docker compose up -d

      # Test the service
      - name: Test Docker Compose Service
        run: |
          sleep 5
          curl http://localhost:8080

